version: '3.4'

services:
  gateway:
    image: gateway
    build:
      context: .
      dockerfile: ApiGateways/Gateway/Dockerfile

  patient:
    image: patient
    build:
      context: .
      dockerfile: Services/Patient/Dockerfile

  patientnotes:
    image: patientnotes
    build:
      context: .
      dockerfile: Services/PatientNotes/Dockerfile

  diabetesrisk:
    image: diabetesrisk
    build:
      context: .
      dockerfile: Services/DiabetesRisk/Dockerfile

  frontend:
    image: frontend
    build:
      context: .
      dockerfile: Web/HealthClinic.Web/Dockerfile