version: '3.4'

services:
  gateway:
    image: gateway
    build:
      context: .
      dockerfile: ApiGateways/Gateway/Dockerfile

  patient:
    image: patient
    build:
      context: .
      dockerfile: Services/Patient/Dockerfile

  frontend:
    image: frontend
    build:
      context: .
      dockerfile: Web/HealthClinic.Web/Dockerfile